const { sendJson, handleCors } = require('../../lib/vercelApi');

module.exports = async (req, res) => {
  if (handleCors(req, res, { methods: ['GET', 'OPTIONS'] })) return;
  // This endpoint used to generate posts on-demand. That behavior is disabled.
  return sendJson(res, 410, { ok: false, error: 'gone', message: 'On-demand blog rendering is disabled. Posts are generated by cron/admin and cached.' });
};
